### ISSUE TITLE
This is a great library

### ISSUE THREAD

**Issue by saolof** [ogrodnek/pyview#1]
Hi!

I just wanted to say some words of encouragement and that this is a really nice library. Liveview is a great paradigm and I've had quite a few cases where I felt that I needed something like this library at work. It looks pretty close to optimal for me.

If there's anything I could consider asking for as a wishlist, it would be to have some documented way of exposing both liveviews and REST endpoints from the same server, with the liveview calling the functions from the other endpoints, so that I can easily add a view that provides a GUI to inspect a service endpoint. Right now I use fastapi-htmx for that.

**Comment by ogrodnek** [comment]
Thanks for the words of encouragement!

I'm not familiar w/ fastapi-htmx, interesting idea, i'll check it out...

**Comment by ogrodnek** [comment]
Thanks again for the feedback, will continue to think about this but closing this issue for now.
