### ISSUE TITLE
Any example of Chat UI?

### ISSUE THREAD

**Issue by nileshtrivedi** [ogrodnek/pyview#8]
I am trying to implement a ChatGPT-like interface and came across Pyview. I was not able to find examples of Chat UI implemented with Pyview. If something like this exists, can you point me to it? If not, I think this would make a great example of PyView's capabilities, especially if it supports features like file uploads in the chat.

**Comment by ogrodnek** [comment]
Hey @nileshtrivedi I put a simple example up here: https://github.com/pyview/pyview-example-ai-chat

**Comment by nileshtrivedi** [comment]
@ogrodnek Is that a private repository? GitHub gives me 404 error on the above link.

**Comment by ogrodnek** [comment]
@nileshtrivedi oops, sorry, should be public now.
